import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Issue_Book extends javax.swing.JFrame {
int id;
    /**
     * Creates new form Issue_Book
     */
    public Issue_Book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Book Issue");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(224, 27, 171, 58);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Your book :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(125, 374, 81, 17);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(422, 370, 51, 32);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(483, 370, 55, 32);

        Date date = new Date();
        jTextField3.setText(dateFormat.format(date));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(456, 11, 82, 20);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"<------Click the botton! " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(224, 103, 188, 247);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("List Of Books");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(102, 103, 104, 35);

        jTextField2.setText("");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(224, 368, 188, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\min\\bg\\700429-beautiful-library-background-image-1920x1080-screen.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 550, 440);

        setSize(new java.awt.Dimension(563, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        Inside_S is=new Inside_S();
        is.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String bookName=jTextField2.getText();
            int stid=Student_login.i;
            try {
                int qty=0;
            PreparedStatement p=JDBCUtil.getQueryShowPayment();
            p.setInt(1, stid);
            ResultSet r=p.executeQuery();
            int check=0;
            if(r.next()){
                check =r.getInt("charges");
            }
            if(check==0){
            PreparedStatement pstmt=JDBCUtil.getQueryIssueBook();
            PreparedStatement pstmt1= JDBCUtil.getQuerybid();
            PreparedStatement pstmt2= JDBCUtil.showBookQTY();
            pstmt2.setString(1, bookName);
            ResultSet rs2= pstmt2.executeQuery();
            if(rs2.next()){
                 qty=rs2.getInt("qty");
                        }
            qty--;
            pstmt.setString(2, bookName);
            pstmt.setString(3,jTextField3.getText());
            pstmt.setInt(4,stid);
            
//            pstmt.setString(5, bookName);
//            pstmt.setString(6,jTextField3.getText());
            
            pstmt1.setString(1,bookName);
            
           ResultSet rs= pstmt1.executeQuery();
            if(rs.next()){
            id =rs.getInt("bid");
                System.out.println("bid="+id);
            }    
            pstmt.setInt(1, id);
            int b=pstmt.executeUpdate();
            PreparedStatement pstmt3=JDBCUtil.getQueryUpdateQTY();
            pstmt3.setInt(1, qty);
            pstmt3.setString(2, bookName);
            pstmt3.executeUpdate();
            if (b!=0){
                JOptionPane.showMessageDialog(null , "Sucessfully added-->"+bookName);
            }
            }
            else{
                JOptionPane.showMessageDialog(null , "Clear your dues Rs."+check);
                setVisible(false);
        Inside_S is=new Inside_S();
        is.setVisible(true);
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      DefaultListModel DFM= new DefaultListModel();
      
    
        try{
            PreparedStatement pstmt= JDBCUtil.showBook();
              
            ResultSet rs;
            rs=pstmt.executeQuery();
            while(rs.next()){
            
                String name = rs.getString("bname");
                 //id=rs.getInt("bid");
                
                DFM.addElement(name);
            }
            
      jList2.setModel(DFM);        
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        String selected=jList2.getSelectedValue().toString();
        jTextField2.setText(selected);
        
    }//GEN-LAST:event_jList2ValueChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Issue_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Issue_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Issue_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Issue_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Issue_Book().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
