import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Remove_book extends javax.swing.JFrame {
        int charges;
        String stname=null;
    /**
     * Creates new form Remove_book
     */
    public Remove_book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Book Returning");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(225, 11, 185, 52);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Enter Book Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(89, 316, 130, 29);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(225, 313, 185, 39);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(419, 311, 81, 39);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(419, 358, 81, 32);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("List of Books");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(98, 69, 121, 31);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<---Click to View issued books!" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(225, 69, 185, 236);

        jTextField2.setEditable(false);
        Date date = new Date();
        jTextField2.setText(dateFormat.format(date));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(451, 11, 94, 20);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Finish");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(272, 358, 71, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\min\\bg\\700429-beautiful-library-background-image-1920x1080-screen.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 440);

        setSize(new java.awt.Dimension(564, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        Inside_S is=new Inside_S();
        is.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int id =Student_login.i;
        System.out.println("sid="+id);
        DefaultListModel DFM= new DefaultListModel();
        try{
            PreparedStatement pstmt=JDBCUtil.getQueryListBook();
            ResultSet rs;
            pstmt.setInt(1, id);
            rs= pstmt.executeQuery();

            while(rs.next()){
            String name=rs.getString("name");
            DFM.addElement(name);
            }
            jList2.setModel(DFM);
            
        }catch(Exception e) {
            e.printStackTrace();
        }
       
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
       String selected=jList2.getSelectedValue().toString();
        jTextField1.setText(selected);
    }//GEN-LAST:event_jList2ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cal_charges=0;
        int qty=0;
        String dfield = jTextField2.getText();
         String bookName=jTextField1.getText();
        int stid=Student_login.i; 
        try {
            Date d1 =null;
            Date d = new SimpleDateFormat("yyyy-MM-dd").parse(dfield);
            PreparedStatement pstmt1=JDBCUtil.getQueryDoi();
             pstmt1.setInt(1, stid);
             pstmt1.setString(2, bookName);
             ResultSet rs= pstmt1.executeQuery();
             if(rs.next()){
             String date1=rs.getString("doi");
             d1 = new SimpleDateFormat("yyyy-MM-dd").parse(date1);
             
             long diff= d1.getTime()- d.getTime();
//             long diffSeconds = diff / 1000 % 60;
//        long diffMinutes = diff / (60 * 1000) % 60;
//        long diffHours = diff / (60 * 60 * 1000);
        int diffInDays = (int) ((d.getTime() - d1.getTime()) / (1000 * 60 * 60 * 24));
      System.out.println("Difference in number of days (2) : " + diffInDays);
            
        if(diffInDays > 15) {
            cal_charges=(diffInDays-15)*5;//5rs delay charges per day
            System.out.println("Difference in number of days (2) : " + diffInDays);
            charges=charges+cal_charges;
            System.out.println("charges="+charges);
        } 
        System.out.println("final charges="+charges);
//        else if (diffHours > 24) {
//
//            System.err.println(">24");
//            
//        } else if ((diffHours == 24) && (diffMinutes >= 1)) {
//            System.err.println("minutes");
//            
//        }
             }
             PreparedStatement pstmt2=JDBCUtil.showBookQTY();
             pstmt2.setString(1, bookName);
             ResultSet rs2=pstmt2.executeQuery();
             if(rs2.next()){
                 qty=rs2.getInt("qty");
             }
             qty++;
             PreparedStatement pstmt3=JDBCUtil.getQueryUpdateQTY();
             pstmt3.setInt(1, qty);
             pstmt3.setString(2, bookName);
             pstmt3.executeUpdate();
   
        } catch (Exception ex) {
            Logger.getLogger(Remove_book.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
       
        try {
       PreparedStatement pstmt =JDBCUtil.getQueryReturnBook();
        pstmt.setInt(1, stid);
        pstmt.setString(2, bookName);
        int b=pstmt.executeUpdate();
              if (b!=0){
              JOptionPane.showMessageDialog(null, "Returned book:"+bookName+"\nID:"+stid);
           }  
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int stid=Student_login.i; 
        try {
            PreparedStatement pstmt3=JDBCUtil.getQueryStudent();
        pstmt3.setInt(1, stid);
        ResultSet rs3=pstmt3.executeQuery();
        
        if(rs3.next()){
        stname=rs3.getString("sname");
            System.out.println("sname=::"+stname);
        }   
            
            PreparedStatement pstmt2=JDBCUtil.getQueryChargeBook();
             pstmt2.setInt(1, stid);
             pstmt2.setString(2, stname);
            pstmt2.setInt(3, charges);
            int b=pstmt2.executeUpdate();
            if(b!=0){
                JOptionPane.showMessageDialog(null, "charges="+charges);
             setVisible(false);
             Inside_S is=new Inside_S();
             is.setVisible(true);
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    /*private void jList1(java.awt.event.ActionEvent evt)
    {
        String s1=jList1.getSelectedValuesList().toString();
        System.out.println("s1"+s1);
    }*/
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Remove_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Remove_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Remove_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Remove_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Remove_book().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
